// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-household.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/_shared.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
async function getUserHousehold(ctx) {
  const supabase = supabaseForUser(ctx);
  const { data, error } = await supabase.from("households").select("id, name, num_adults, num_children, child_age_bands").eq("owner_id", ctx.getUserId()).maybeSingle();
  if (error) throw new Error(error.message);
  return data;
}
var DAY_NAMES = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
function dayName(dow) {
  return DAY_NAMES[dow] ?? `Day ${dow}`;
}

// src/lib/mcp/tools/get-household.ts
var get_household_default = defineTool({
  name: "get_household",
  title: "Get household",
  description: "Get the signed-in user's household profile: name, number of adults, number of children, and child age bands.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const household = await getUserHousehold(ctx);
    if (!household) {
      return {
        content: [{ type: "text", text: "No household found for this account yet." }]
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(household) }],
      structuredContent: { household }
    };
  }
});

// src/lib/mcp/tools/get-current-plan.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_current_plan_default = defineTool2({
  name: "get_current_plan",
  title: "Get current dinner plan",
  description: "Get the signed-in user's most recent weekly dinner plan, including each day's meal name, description, mode, prep time, and per-serving nutrition.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const household = await getUserHousehold(ctx);
    if (!household) {
      return { content: [{ type: "text", text: "No household found for this account yet." }] };
    }
    const supabase = supabaseForUser(ctx);
    const { data: plan, error: planError } = await supabase.from("weekly_plans").select("id, week_start, reality_score, reality_message").eq("household_id", household.id).order("week_start", { ascending: false }).limit(1).maybeSingle();
    if (planError) throw new Error(planError.message);
    if (!plan) {
      return { content: [{ type: "text", text: "No weekly plans found yet." }] };
    }
    const { data: days, error: daysError } = await supabase.from("plan_days").select(
      "day_of_week, meal_mode, meal_name, meal_description, cuisine_type, prep_time_minutes, calories, protein_g, carbs_g, fat_g, fiber_g"
    ).eq("plan_id", plan.id).order("day_of_week", { ascending: true });
    if (daysError) throw new Error(daysError.message);
    const result = {
      week_start: plan.week_start,
      reality_score: plan.reality_score,
      reality_message: plan.reality_message,
      days: (days ?? []).map((d) => ({
        day: dayName(d.day_of_week),
        mode: d.meal_mode,
        meal: d.meal_name,
        description: d.meal_description,
        cuisine: d.cuisine_type,
        prep_time_minutes: d.prep_time_minutes,
        nutrition_per_serving: {
          calories: d.calories,
          protein_g: d.protein_g,
          carbs_g: d.carbs_g,
          fat_g: d.fat_g,
          fiber_g: d.fiber_g
        }
      }))
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/get-grocery-list.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_grocery_list_default = defineTool3({
  name: "get_grocery_list",
  title: "Get grocery list",
  description: "Get the grocery list for the signed-in user's most recent weekly plan, grouped by category, with checked state and quantities.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const household = await getUserHousehold(ctx);
    if (!household) {
      return { content: [{ type: "text", text: "No household found for this account yet." }] };
    }
    const supabase = supabaseForUser(ctx);
    const { data: plan, error: planError } = await supabase.from("weekly_plans").select("id, week_start").eq("household_id", household.id).order("week_start", { ascending: false }).limit(1).maybeSingle();
    if (planError) throw new Error(planError.message);
    if (!plan) {
      return { content: [{ type: "text", text: "No weekly plans found yet." }] };
    }
    const { data: items, error: itemsError } = await supabase.from("grocery_items").select("item_name, quantity, category, is_checked, is_staple, source").eq("plan_id", plan.id).order("category", { ascending: true });
    if (itemsError) throw new Error(itemsError.message);
    const result = {
      week_start: plan.week_start,
      total_items: items?.length ?? 0,
      items: (items ?? []).map((i) => ({
        name: i.item_name,
        quantity: i.quantity,
        category: i.category,
        checked: i.is_checked ?? false,
        staple: i.is_staple ?? false,
        source: i.source
      }))
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-saved-meals.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
var list_saved_meals_default = defineTool4({
  name: "list_saved_meals",
  title: "List saved meals",
  description: "List the meals the signed-in user's household has saved to their custom library, with frequency and whether they are included in planning.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const household = await getUserHousehold(ctx);
    if (!household) {
      return { content: [{ type: "text", text: "No household found for this account yet." }] };
    }
    const supabase = supabaseForUser(ctx);
    const { data: meals, error } = await supabase.from("saved_meals").select("meal_name, meal_description, frequency, include_in_plan").eq("household_id", household.id).order("created_at", { ascending: false });
    if (error) throw new Error(error.message);
    const result = {
      total: meals?.length ?? 0,
      meals: (meals ?? []).map((m) => ({
        name: m.meal_name,
        description: m.meal_description,
        frequency: m.frequency,
        include_in_plan: m.include_in_plan
      }))
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "khotrjtyyrtyuvlzlzrd";
var mcp_default = defineMcp({
  name: "family-food-os-mcp",
  title: "Family Food OS",
  version: "0.1.0",
  instructions: "Tools for Family Food OS, a weekly family dinner planning system. Use these to read the signed-in user's household profile, their current weekly dinner plan with per-serving nutrition, their grocery list, and their saved meal library.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_household_default, get_current_plan_default, get_grocery_list_default, list_saved_meals_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
