// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/get-household.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/_shared.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
async function getUserHousehold(ctx) {
  const supabase = supabaseForUser(ctx);
  const { data, error } = await supabase.from("households").select("id, name, num_adults, num_children, child_age_bands").eq("owner_id", ctx.getUserId()).maybeSingle();
  if (error) throw new Error(error.message);
  return data;
}
var DAY_NAMES = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
function dayName(dow) {
  return DAY_NAMES[dow] ?? `Day ${dow}`;
}

// src/lib/mcp/tools/get-household.ts
var get_household_default = defineTool({
  name: "get_household",
  title: "Get household",
  description: "Get the signed-in user's household profile: name, number of adults, number of children, and child age bands.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const household = await getUserHousehold(ctx);
    if (!household) {
      return {
        content: [{ type: "text", text: "No household found for this account yet." }]
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(household) }],
      structuredContent: { household }
    };
  }
});

// src/lib/mcp/tools/get-current-plan.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
var get_current_plan_default = defineTool2({
  name: "get_current_plan",
  title: "Get current dinner plan",
  description: "Get the signed-in user's most recent weekly dinner plan, including each day's meal name, description, mode, prep time, and per-serving nutrition.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const household = await getUserHousehold(ctx);
    if (!household) {
      return { content: [{ type: "text", text: "No household found for this account yet." }] };
    }
    const supabase = supabaseForUser(ctx);
    const { data: plan, error: planError } = await supabase.from("weekly_plans").select("id, week_start, reality_score, reality_message").eq("household_id", household.id).order("week_start", { ascending: false }).limit(1).maybeSingle();
    if (planError) throw new Error(planError.message);
    if (!plan) {
      return { content: [{ type: "text", text: "No weekly plans found yet." }] };
    }
    const { data: days, error: daysError } = await supabase.from("plan_days").select(
      "day_of_week, meal_mode, meal_name, meal_description, cuisine_type, prep_time_minutes, calories, protein_g, carbs_g, fat_g, fiber_g"
    ).eq("plan_id", plan.id).order("day_of_week", { ascending: true });
    if (daysError) throw new Error(daysError.message);
    const result = {
      week_start: plan.week_start,
      reality_score: plan.reality_score,
      reality_message: plan.reality_message,
      days: (days ?? []).map((d) => ({
        day: dayName(d.day_of_week),
        mode: d.meal_mode,
        meal: d.meal_name,
        description: d.meal_description,
        cuisine: d.cuisine_type,
        prep_time_minutes: d.prep_time_minutes,
        nutrition_per_serving: {
          calories: d.calories,
          protein_g: d.protein_g,
          carbs_g: d.carbs_g,
          fat_g: d.fat_g,
          fiber_g: d.fiber_g
        }
      }))
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/get-grocery-list.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
var get_grocery_list_default = defineTool3({
  name: "get_grocery_list",
  title: "Get grocery list",
  description: "Get the grocery list for the signed-in user's most recent weekly plan, grouped by category, with checked state and quantities.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const household = await getUserHousehold(ctx);
    if (!household) {
      return { content: [{ type: "text", text: "No household found for this account yet." }] };
    }
    const supabase = supabaseForUser(ctx);
    const { data: plan, error: planError } = await supabase.from("weekly_plans").select("id, week_start").eq("household_id", household.id).order("week_start", { ascending: false }).limit(1).maybeSingle();
    if (planError) throw new Error(planError.message);
    if (!plan) {
      return { content: [{ type: "text", text: "No weekly plans found yet." }] };
    }
    const { data: items, error: itemsError } = await supabase.from("grocery_items").select("item_name, quantity, category, is_checked, is_staple, source").eq("plan_id", plan.id).order("category", { ascending: true });
    if (itemsError) throw new Error(itemsError.message);
    const result = {
      week_start: plan.week_start,
      total_items: items?.length ?? 0,
      items: (items ?? []).map((i) => ({
        name: i.item_name,
        quantity: i.quantity,
        category: i.category,
        checked: i.is_checked ?? false,
        staple: i.is_staple ?? false,
        source: i.source
      }))
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-saved-meals.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
var list_saved_meals_default = defineTool4({
  name: "list_saved_meals",
  title: "List saved meals",
  description: "List the meals the signed-in user's household has saved to their custom library, with frequency and whether they are included in planning.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const household = await getUserHousehold(ctx);
    if (!household) {
      return { content: [{ type: "text", text: "No household found for this account yet." }] };
    }
    const supabase = supabaseForUser(ctx);
    const { data: meals, error } = await supabase.from("saved_meals").select("meal_name, meal_description, frequency, include_in_plan").eq("household_id", household.id).order("created_at", { ascending: false });
    if (error) throw new Error(error.message);
    const result = {
      total: meals?.length ?? 0,
      meals: (meals ?? []).map((m) => ({
        name: m.meal_name,
        description: m.meal_description,
        frequency: m.frequency,
        include_in_plan: m.include_in_plan
      }))
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/search-saved-meals.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
var PROTEIN_TAGS = [
  { tag: "chicken", patterns: /\b(chicken|poultry|rotisserie)\b/i },
  { tag: "beef", patterns: /\b(beef|steak|burger|meatball|meatloaf|brisket)\b/i },
  { tag: "pork", patterns: /\b(pork|bacon|ham|sausage|chorizo|prosciutto)\b/i },
  { tag: "turkey", patterns: /\b(turkey)\b/i },
  { tag: "lamb", patterns: /\b(lamb)\b/i },
  { tag: "fish", patterns: /\b(salmon|tuna|cod|tilapia|halibut|trout|fish|snapper|mahi)\b/i },
  { tag: "seafood", patterns: /\b(shrimp|prawn|scallop|crab|lobster|clam|mussel|calamari|squid)\b/i },
  { tag: "tofu", patterns: /\b(tofu|tempeh|seitan|edamame)\b/i },
  { tag: "beans", patterns: /\b(bean|lentil|chickpea|garbanzo|dal|dahl)\b/i },
  { tag: "eggs", patterns: /\b(egg|frittata|omelet|omelette|quiche|shakshuka)\b/i },
  { tag: "cheese", patterns: /\b(cheese|paneer|halloumi|ricotta|mozzarella|parmesan)\b/i }
];
var TYPE_TAGS = [
  { tag: "pasta", patterns: /\b(pasta|spaghetti|linguine|penne|rigatoni|rotini|fettuccine|lasagna|ravioli|gnocchi|mac and cheese|carbonara|bolognese|alfredo)\b/i },
  { tag: "pizza", patterns: /\b(pizza|flatbread|calzone)\b/i },
  { tag: "taco", patterns: /\b(taco|burrito|quesadilla|enchilada|fajita|tostada|nachos)\b/i },
  { tag: "stir-fry", patterns: /\b(stir[- ]fry|stirfry|wok)\b/i },
  { tag: "curry", patterns: /\b(curry|masala|tikka|korma|vindaloo|thai red|thai green)\b/i },
  { tag: "soup", patterns: /\b(soup|stew|chili|chowder|bisque|ramen|pho|minestrone)\b/i },
  { tag: "salad", patterns: /\b(salad|bowl|grain bowl|buddha bowl|poke)\b/i },
  { tag: "sandwich", patterns: /\b(sandwich|sub|hoagie|wrap|panini|melt|gyro)\b/i },
  { tag: "rice", patterns: /\b(rice|risotto|paella|biryani|pilaf|jambalaya|fried rice)\b/i },
  { tag: "grill", patterns: /\b(grill|grilled|bbq|barbecue|kebab|kabob|skewer)\b/i },
  { tag: "roast", patterns: /\b(roast|roasted|baked|sheet[- ]pan|casserole|bake)\b/i },
  { tag: "breakfast-for-dinner", patterns: /\b(pancake|waffle|french toast|breakfast)\b/i }
];
function deriveTags(text) {
  return {
    type_tags: TYPE_TAGS.filter((t) => t.patterns.test(text)).map((t) => t.tag),
    protein_tags: PROTEIN_TAGS.filter((t) => t.patterns.test(text)).map((t) => t.tag)
  };
}
function tokenize(q) {
  return q.toLowerCase().split(/[^a-z0-9]+/).filter((t) => t.length >= 2);
}
function scoreMeal(name, description, tokens) {
  const n = (name ?? "").toLowerCase();
  const d = (description ?? "").toLowerCase();
  let score = 0;
  for (const t of tokens) {
    const wordRe = new RegExp(`\\b${t.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\b`);
    if (wordRe.test(n)) score += 10;
    else if (n.includes(t)) score += 6;
    if (wordRe.test(d)) score += 3;
    else if (d.includes(t)) score += 1;
  }
  const phrase = tokens.join(" ");
  if (phrase && n.includes(phrase)) score += 5;
  return score;
}
var search_saved_meals_default = defineTool5({
  name: "search_saved_meals",
  title: "Search saved meals",
  description: "Search the signed-in user's saved meal library by name or description keywords. Results are ranked by relevance (name matches beat description matches) and annotated with derived tags for meal type (pasta, taco, curry, ...) and protein (chicken, salmon, tofu, ...) so an assistant can quickly filter or propose one to add to the weekly plan.",
  inputSchema: {
    query: z.string().trim().min(1).describe("Keywords to search for in the meal name or description (case-insensitive)."),
    limit: z.number().int().min(1).max(25).optional().describe("Maximum number of matches to return, after relevance ranking. Defaults to 10.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const household = await getUserHousehold(ctx);
    if (!household) {
      return { content: [{ type: "text", text: "No household found for this account yet." }] };
    }
    const max = limit ?? 10;
    const tokens = tokenize(query);
    if (tokens.length === 0) {
      return { content: [{ type: "text", text: "Query has no searchable terms." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const orFilter = tokens.flatMap((t) => {
      const p = `%${t.replace(/[,%()*]/g, " ")}%`;
      return [`meal_name.ilike.${p}`, `meal_description.ilike.${p}`];
    }).join(",");
    const { data: meals, error } = await supabase.from("saved_meals").select("id, meal_name, meal_description, frequency, include_in_plan, created_at").eq("household_id", household.id).or(orFilter).limit(Math.min(max * 4, 100));
    if (error) throw new Error(error.message);
    const ranked = (meals ?? []).map((m) => {
      const score = scoreMeal(m.meal_name ?? "", m.meal_description ?? null, tokens);
      const tags = deriveTags(`${m.meal_name ?? ""} ${m.meal_description ?? ""}`);
      return { m, score, tags };
    }).filter((r) => r.score > 0).sort((a, b) => {
      if (b.score !== a.score) return b.score - a.score;
      const at = a.m.created_at ? Date.parse(a.m.created_at) : 0;
      const bt = b.m.created_at ? Date.parse(b.m.created_at) : 0;
      return bt - at;
    }).slice(0, max);
    const result = {
      query,
      total: ranked.length,
      meals: ranked.map(({ m, score, tags }) => ({
        id: m.id,
        name: m.meal_name,
        description: m.meal_description,
        frequency: m.frequency,
        include_in_plan: m.include_in_plan,
        relevance: score,
        type_tags: tags.type_tags,
        protein_tags: tags.protein_tags
      })),
      hint: ranked.length === 0 ? "No saved meals matched. Try a shorter or different keyword." : "Results are ordered by relevance. To add one to the plan, tell the user which day to swap it onto \u2014 swapping runs in the app."
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "khotrjtyyrtyuvlzlzrd";
var mcp_default = defineMcp({
  name: "family-food-os-mcp",
  title: "Family Food OS",
  version: "0.1.0",
  instructions: "Tools for Family Food OS, a weekly family dinner planning system. Use these to read the signed-in user's household profile, their current weekly dinner plan with per-serving nutrition, their grocery list, and their saved meal library.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_household_default, get_current_plan_default, get_grocery_list_default, list_saved_meals_default, search_saved_meals_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
